FROM debian:latest

WORKDIR /warp

COPY install.sh healthcheck.sh start.sh /warp/

RUN chmod +x /warp/*

RUN ls -l /warp

RUN /warp/install.sh

HEALTHCHECK --start-period=20s --interval=1m --timeout=10s --retries=3 CMD ./healthcheck.sh || exit 1

CMD [ "/warp/start.sh" ]

