
FROM alpine:latest

RUN apk add restic rclone


VOLUME [ "/data", "/config" ]

ENV RESTIC_REPOSITORY=/tmp/repository \
    RESTIC_PASSWORD=123455 \
    RCLONE_CONFIG=/config/rclone \
    SCHEDULE="0 */6 * * *"
    
COPY backup /usr/bin/backup
COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh && \
    chmod +x /usr/bin/backup && \
    touch /etc/rclone.conf && \
    echo "${SCHEDULE} /usr/bin/backup" > /etc/crontabs/root
    

ENTRYPOINT ["/entrypoint.sh"]

CMD ["crond", "-f"]