FROM golang:1.18 as builder

WORKDIR /root

RUN go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
RUN xcaddy build --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive --with github.com/caddy-dns/cloudflare@master

FROM debian:latest

ENV DOMAIN=example.com
ENV HTTP_PORT=8080
ENV HTTPS_PORT=8443
ENV USERNAME=username
ENV PASSWORD=password
ENV UPSTREAM=example.com:80
ENV CF_API_TOKEN=1234567890


VOLUME [ "/root/.local/share/caddy" ]

WORKDIR /srv

COPY --from=builder /root/caddy ./
COPY ./Caddyfile.template ./start.sh ./

RUN apt update && apt install -y gettext libcap2-bin && \
    setcap cap_net_bind_service=+ep caddy && \
    apt clean autoclean && \
    apt autoremove --yes && \
    rm -rf /var/lib/{apt,dpkg,cache,log}/

ENTRYPOINT [ "/srv/start.sh" ]
