name: Restic

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 1'

env:
  DOCKER_REPOSITORY: restic
  CONTEXT: ./restic

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create docker image tag
        run: echo VERSION=$(date +%y%m%d%H%M%S) >> $GITHUB_ENV
      - name: Docker setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Docker setup Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./${{ env.CONTEXT }}
          file: ./${{ env.CONTEXT }}/Containerfile
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64/v8
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_REPOSITORY }}:${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_REPOSITORY }}:latest