name: Docker build

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 1'

env: 
  DOCKER_REPOSITORY: wxxxcxx/xray

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Docker setup QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Docker setup Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        
    - name: Create image tag
      run: echo DATE_TAG=$(date +%y%m%d%H%M%S) >> $GITHUB_ENV
      
    - name: Build and push docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        platforms: |
          linux/amd64
          linux/arm64/v8
        tags: |
          ${{ env.DOCKER_REPOSITORY }}:${{ env.DATE_TAG }}
          ${{ env.DOCKER_REPOSITORY }}:latest